config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :guesthouses, only: %i[show new create edit update] do
    get 'search', on: :collection
  end

  resources :rooms, only: %i[show new create edit update] do
    resources :custom_prices, only: %i[show new create edit update destroy]
    resources :reservations, only: %i[show new create edit update destroy show_total_price] do
      get 'show_total_price', on: :member
    end
  end

  get 'home/guesthouses_by_city/:city', to: 'home#guesthouses_by_city', as: :guesthouses_by_city

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/guesthouses_controller.rb
class GuesthousesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :set_guesthouse, only: %i[show edit update]

  def new
    if current_user.guesthouse.present?
      flash.alert = 'You already have a registered guesthouse.'
      redirect_to current_user.guesthouse
    else
      @guesthouse = current_user.build_guesthouse
    end
  end

  def create
    @guesthouse = current_user.build_guesthouse(guesthouse_params)

    if @guesthouse.save
      redirect_to @guesthouse, notice: 'Guesthouse registered successfully!'
    else
      flash.now.alert = 'Unable to register guesthouse!'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if current_user == @guesthouse.user
      @rooms = @guesthouse.rooms
    else
      @rooms = @guesthouse.rooms.disponivel
    end
  end

  def search
    @query = params['query']
    @guesthouses = Guesthouse.joins(:full_address).where('brand_name LIKE ? OR neighborhood LIKE ? OR city LIKE ?', "%#{@query}%", "%#{@query}%", "%#{@query}%").order(:brand_name)
  end

  def edit
    unless current_user == @guesthouse.user
      flash.alert = "You don't have permission to edit this guesthouse."
      redirect_to guesthouse_path
    end
  end

  def update
    if @guesthouse.update(guesthouse_params)
      redirect_to @guesthouse, notice: 'Guesthouse updated successfully!'
    else
      flash.now.alert = 'Unable to update the guesthouse'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def guesthouse_params
    params.require(:guesthouse).permit(
      :brand_name,
      :corporate_name,
      :register_number,
      :phone_number,
      :email,
      :description,
      :pet_friendly,
      :terms,
      :check_in_time,
      :check_out_time,
      :status,
      full_address_attributes: [:address, :number, :neighborhood, :city, :state, :zip_code, :complement],
      payment_method_ids: []
      )
  end

  def set_guesthouse
    @guesthouse = Guesthouse.find(params[:id])
  end
end

app/views/guesthouses/_form.html.erb
<div class='guesthouse-form'>
  <%= form_with model: @guesthouse do |f| %>
    <div>
      <%= f.label :brand_name, 'Brand Name' %>
      <%= f.text_field :brand_name %>

      <%= f.label :corporate_name, 'Corporate Name' %>
      <%= f.text_field :corporate_name %>
    </div> 
    <div>
      <%= f.label :register_number, 'Register Number' %>
      <%= f.text_field :register_number %>
    </div>
    <div>
      <%= f.label :phone_number, 'Phone Number' %>
      <%= f.number_field :phone_number %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>  
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :pet_friendly, 'Pet Friendly' %>
      <%= f.select :pet_friendly, ['Sim', 'Não'] %>
    </div>
    <div>
      <%= f.label :terms %>
      <%= f.text_area :terms %>
    </div>
    <div>
      <%= f.label :check_in_time %>
      <%= f.time_field :check_in_time %>

      <%= f.label :check_out_time %>
      <%= f.time_field :check_out_time %>  </div>
    
    <div>
      <%= f.label :status %>
      <%= f.select :status, ['ativa', 'inativa'] %>
    </div>
  <br>
    <%= f.fields_for :full_address, f.object.full_address || FullAddress.new do |fa| %>Full Address
      <div>
        <%= fa.label :address %>
        <%= fa.text_field :address %>

        <%= fa.label :number %>
        <%= fa.number_field :number %>

        <%= fa.label :neighborhood %>
        <%= fa.text_field :neighborhood %>

        <%= fa.label :city %>
        <%= fa.text_field :city %>

        <%= fa.label :state %>
        <%= fa.text_field :state %>
      </div>
      <div>
        <%= fa.label :zip_code, 'Zip Code' %>
        <%= fa.number_field :zip_code %>

        <%= fa.label :complement %>
        <%= fa.text_field :complement %>
      </div> 
    <% end %>

    <br>

      <%= f.label :payment_method_ids, 'Payment Methods:' %>
      <%= f.collection_check_boxes :payment_method_ids, PaymentMethod.all, :id, :name %>
      
    <div>
      <p><%= f.submit 'Send' %></p>
    </div>
  <% end %>
</div>

app/views/guesthouses/_guesthouse.html.erb
<dl>       
  <strong><dt>Corporate Name</dt></strong>
  <dd><%= @guesthouse.corporate_name %></dd>  

  <strong><dt>Register Number</dt></strong>
  <dd><%= @guesthouse.register_number %></dd>  

  <strong><dt>Phone Number</dt></strong>
  <dd><%= @guesthouse.phone_number %></dd>  

  <strong><dt>Email</dt></strong>
  <dd><%= @guesthouse.email %></dd>  

  <strong><dt>Full Address</dt></strong>
  <dd>
    <%= @guesthouse.full_address.address %>, <%= @guesthouse.full_address.number %> - 
    <%= @guesthouse.full_address.neighborhood %> - <%= @guesthouse.full_address.city %> - 
    <%= @guesthouse.full_address.state %> - Zip Code: <%= @guesthouse.full_address.zip_code %> -
    Complement: <%= @guesthouse.full_address.complement %>
  </dd>  

  <strong><dt>Payment Methods</dt></strong>
  <% @guesthouse.payment_methods.each do |pm| %>
    <dd><%= pm.name %></dd>
  <% end %>

  <strong><dt>Pet Friendly</dt></strong>
  <dd><%= @guesthouse.pet_friendly %></dd>

  <strong><dt>Check in Time</dt></strong>
  <dd><%= @guesthouse.check_in_time %></dd>

  <strong><dt>Check out Time</dt></strong>
  <dd><%= @guesthouse.check_out_time %></dd>

  <strong><dt>Description</dt></strong>
  <dd><%= @guesthouse.description %></dd>

  <strong><dt>Terms</dt></strong>
  <dd><%= @guesthouse.terms %></dd>

  <strong><dt>Status</dt></strong>
  <dd><%= @guesthouse.status %></dd>
</dl>

app/views/guesthouses/_guesthouse_guest.html.erb
<dl>         
  <strong><dt>Phone Number</dt></strong>
  <dd><%= @guesthouse.phone_number %></dd>  

  <strong><dt>Email</dt></strong>
  <dd><%= @guesthouse.email %></dd>  

  <strong><dt>Full Address</dt></strong>
  <dd>
    <%= @guesthouse.full_address.address %>, <%= @guesthouse.full_address.number %> - 
    <%= @guesthouse.full_address.neighborhood %> - <%= @guesthouse.full_address.city %> - 
    <%= @guesthouse.full_address.state %> - Zip Code: <%= @guesthouse.full_address.zip_code %> -
    Complement: <%= @guesthouse.full_address.complement %>
  </dd>  

  <strong><dt>Payment Methods</dt></strong>
  <% @guesthouse.payment_methods.each do |pm| %>
    <dd><%= pm.name %></dd>
  <% end %>

  <strong><dt>Pet Friendly</dt></strong>
  <dd><%= @guesthouse.pet_friendly %></dd>

  <strong><dt>Check in Time</dt></strong>
  <dd><%= @guesthouse.check_in_time %></dd>

  <strong><dt>Check out Time</dt></strong>
  <dd><%= @guesthouse.check_out_time %></dd>

  <strong><dt>Description</dt></strong>
  <dd><%= @guesthouse.description %></dd>

  <strong><dt>Terms</dt></strong>
  <dd><%= @guesthouse.terms %></dd>  
</dl>

app/views/guesthouses/_guesthouse_host.html.erb
<dl>       
  <strong><dt>Corporate Name</dt></strong>
  <dd><%= @guesthouse.corporate_name %></dd>  

  <strong><dt>Register Number</dt></strong>
  <dd><%= @guesthouse.register_number %></dd>  

  <strong><dt>Phone Number</dt></strong>
  <dd><%= @guesthouse.phone_number %></dd>  

  <strong><dt>Email</dt></strong>
  <dd><%= @guesthouse.email %></dd>  

  <strong><dt>Full Address</dt></strong>
  <dd>
    <%= @guesthouse.full_address.address %>, <%= @guesthouse.full_address.number %> - 
    <%= @guesthouse.full_address.neighborhood %> - <%= @guesthouse.full_address.city %> - 
    <%= @guesthouse.full_address.state %> - Zip Code: <%= @guesthouse.full_address.zip_code %> -
    Complement: <%= @guesthouse.full_address.complement %>
  </dd>  

  <strong><dt>Payment Methods</dt></strong>
  <% @guesthouse.payment_methods.each do |pm| %>
    <dd><%= pm.name %></dd>
  <% end %>

  <strong><dt>Pet Friendly</dt></strong>
  <dd><%= @guesthouse.pet_friendly %></dd>

  <strong><dt>Check in Time</dt></strong>
  <dd><%= @guesthouse.check_in_time %></dd>

  <strong><dt>Check out Time</dt></strong>
  <dd><%= @guesthouse.check_out_time %></dd>

  <strong><dt>Description</dt></strong>
  <dd><%= @guesthouse.description %></dd>

  <strong><dt>Terms</dt></strong>
  <dd><%= @guesthouse.terms %></dd>

  <strong><dt>Status</dt></strong>
  <dd><%= @guesthouse.status %></dd>
</dl>

app/views/guesthouses/_rooms.html.erb
<% @rooms.each do |r| %>
  <div style='border: 1px solid'>
    <h3>- <%= r.name %> -</h3>
    <div>
      <dl>
        <strong><dt>Description</dt></strong>
        <dd><%= r.description %></dd>

        <strong><dt>Maximum Guests</dt></strong>
        <dd><%= r.maximum_guests %></dd>

        <strong><dt>Dimension</dt></strong>
        <dd><%= r.dimension %></dd>

        <strong><dt>Amenities</dt></strong>
        <% r.amenities.each do |a| %>
          <dd><%= a.name %></dd>
        <% end %>

        <strong><dt>Daily Price</dt></strong>
        <dd>$<%= r.daily_price %></dd>

        <strong><dt>Status</dt></strong>
        <dd><%= r.status %></dd>

        <strong><dt>Custom Price</dt></strong>
        <dd>           
          De <%= r.custom_price.start_date %> até <%= r.custom_price.end_date %>
        </dd>
        <dd>
          $<%= r.custom_price.daily_price %>
        </dd>
      </dl>

      <% if current_user == @guesthouse.user %>
        <p><%= link_to 'Edit Room', edit_room_path %></p>
      <% end %>
    </div>    
  </div>
  <br>
<% end %>

app/views/guesthouses/_rooms_guest.html.erb
<h2>Rooms</h2>

<% @rooms.each do |r| %>
  <div style='border: 1px solid'>
    <h3>
      <% if current_user == @guesthouse.user %>
        <%= link_to r.name, r %>
      <% else %>
        <%= r.name %>
      <% end %>
    </h3>
    <div>
      <dl>
        <strong><dt>Description</dt></strong>
        <dd><%= r.description %></dd>

        <strong><dt>Maximum Guests</dt></strong>
        <dd><%= r.maximum_guests %></dd>

        <strong><dt>Dimension</dt></strong>
        <dd><%= r.dimension %></dd>

        <strong><dt>Amenities</dt></strong>
        <% r.amenities.each do |a| %>
          <dd><%= a.name %></dd>
        <% end %>

        <strong><dt>Daily Price</dt></strong>
        <dd>$<%= r.daily_price %></dd>
      </dl>

      <p><%= link_to 'Book', new_room_reservation_path(r) %></p>

      <% if current_user == @guesthouse.user %>
        <p><%= link_to 'Edit Room', edit_room_path %></p>
      <% end %>
    </div>    
  </div>
  <br>
<% end %>

app/views/guesthouses/_rooms_host.html.erb
<h2>Rooms</h2>

<% @rooms.each do |r| %>
  <div style='border: 1px solid'>
    <h3>
      <% if current_user == @guesthouse.user %>
        <%= link_to r.name, r %>
      <% else %>
        <%= r.name %>
      <% end %>
    </h3>
    <div>
      <dl>
        <strong><dt>Description</dt></strong>
        <dd><%= r.description %></dd>

        <strong><dt>Maximum Guests</dt></strong>
        <dd><%= r.maximum_guests %></dd>

        <strong><dt>Dimension</dt></strong>
        <dd><%= r.dimension %></dd>

        <strong><dt>Amenities</dt></strong>
        <% r.amenities.each do |a| %>
          <dd><%= a.name %></dd>
        <% end %>

        <strong><dt>Status</dt></strong>
        <dd><%= r.status %></dd>

        <strong><dt>Daily Price</dt></strong>
        <dd>$<%= r.daily_price %></dd>             
      </dl>

      <% if current_user == @guesthouse.user %>
        <p><%= link_to 'Edit Room', edit_room_path(r) %></p>
      <% end %>
    </div>    
  </div>
  <br>
<% end %>

app/views/guesthouses/edit.html.erb
<h1>Edit Guesthouse</h1>

<% if @guesthouse.errors.any? %>
  <p>Check the errors below:</p>
  <ul>
    <% @guesthouse.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/guesthouses/new.html.erb
<h1>New Guesthouse</h1>

<%= form_with model: @guesthouse do |f| %>
  <div>
    <%= f.label :brand_name, 'Brand Name' %>
    <%= f.text_field :brand_name %>

    <%= f.label :corporate_name, 'Corporate Name' %>
    <%= f.text_field :corporate_name %>
  </div> 
  <div>
    <%= f.label :register_number, 'Register Number' %>
    <%= f.text_field :register_number %>
  </div>
  <div>
    <%= f.label :phone_number, 'Phone Number' %>
    <%= f.number_field :phone_number %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>  
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :pet_friendly, 'Pet Friendly' %>
    <%= f.select :pet_friendly, ['Sim', 'Não'] %>
  </div>
  <div>
    <%= f.label :terms %>
    <%= f.text_area :terms %>
  </div>
  <div>
    <%= f.label :check_in_time %>
    <%= f.time_field :check_in_time %>

    <%= f.label :check_out_time %>
    <%= f.time_field :check_out_time %>  </div>
  
  <div>
    <%= f.label :status %>
    <%= f.select :status, ['Ativa', 'Inativa'] %>
  </div>
<br>
  <%= f.fields_for :full_address, FullAddress.new do |fa| %>Full Address
    <div>
      <%= fa.label :address %>
      <%= fa.text_field :address %>

      <%= fa.label :number %>
      <%= fa.number_field :number %>

      <%= fa.label :neighborhood %>
      <%= fa.text_field :neighborhood %>

      <%= fa.label :city %>
      <%= fa.text_field :city %>

      <%= fa.label :state %>
      <%= fa.text_field :state %>
    </div>
    <div>
      <%= fa.label :zip_code, 'Zip Code' %>
      <%= fa.number_field :zip_code %>

      <%= fa.label :complement %>
      <%= fa.text_field :complement %>
    </div> 
  <% end %>
  <br>
    <%= f.label :payment_method_ids, 'Payment Methods:' %>
    <%= f.collection_check_boxes :payment_method_ids, PaymentMethod.all, :id, :name %>
  <div>
    <p><%= f.submit 'Send' %></p>
  </div>
<% end %>

app/views/guesthouses/search.html.erb
<h1>Search results for: <%= @query %></h1>

<% @guesthouses.each do |g| %>
  <p><%= @guesthouses.count %> found</p>

  <div  style='border: 1px solid'>
    <h2><%= link_to g.brand_name, g %></h2>
    <div>              
      <h3><%= g.full_address.city %> - <%= g.full_address.state %></h3>
    </div>  
  </div> 
  <br> 
<% end %>

app/views/guesthouses/show.html.erb
<h1><%= @guesthouse.brand_name %></h1>
<hr>
<% if current_user == @guesthouse.user %>
  <%= render 'guesthouse_host' %>
  <p><%= link_to 'Edit Guesthouse', edit_guesthouse_path %></p>
  <hr>
  <%= render 'rooms_host' %>
  <p><%= link_to 'Register Room', new_room_path %></p>
<% else %>
  <%= render 'guesthouse_guest' %>
  <hr>
  <%= render 'rooms_guest' %>
<% end %>

<% if @rooms.empty? %>
  <p>There are no registered rooms!</p>
<% end %>