config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :guesthouses, only: %i[show new create edit update] do
    get 'search', on: :collection
  end

  resources :rooms, only: %i[show new create edit update] do
    resources :custom_prices, only: %i[show new create edit update destroy]
    resources :reservations, only: %i[show new create edit update destroy show_total_price] do
      get 'show_total_price', on: :member
    end
  end

  get 'home/guesthouses_by_city/:city', to: 'home#guesthouses_by_city', as: :guesthouses_by_city

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_guesthouses, only: [:index, :guesthouses_by_city]

  def index
    @recent_guesthouses = @guesthouses.ativa.order(created_at: :desc).limit(3)
    @other_guesthouses = other_guesthouses

    @cities = cities_with_guesthouses
  end

  def guesthouses_by_city
    @city = params[:city]
    @guesthouses = @guesthouses.ativa.joins(:full_address).where(full_addresses: { city: @city }).order(:brand_name)
  end

  private

  def load_guesthouses
    @guesthouses =
      if user_signed_in?
        Guesthouse.all.or(Guesthouse.where(user_id: current_user.id))
      else
        Guesthouse.all
      end
  end

  def other_guesthouses
    if user_signed_in?
      @guesthouses.ativa.where.not(id: @recent_guesthouses.pluck(:id)).or(Guesthouse.where(user_id: current_user.id))
    else
      @guesthouses.ativa.where.not(id: @recent_guesthouses.pluck(:id))
    end.uniq
  end

  def cities_with_guesthouses
    @guesthouses.ativa.joins(:full_address).pluck(:city).compact.uniq
  end
end

app/views/home/guesthouses_by_city.html.erb
<h1>Guesthouses in <%= @city %></h1>

<% if @guesthouses.present? %>  
  <% @guesthouses.each do |guesthouse| %>
    <div  style='border: 1px solid'>
      <h2><%= link_to guesthouse.brand_name, guesthouse_path(guesthouse) %></h2>
      <h3><%= guesthouse.full_address.city %> - <%= guesthouse.full_address.state %></h3>
    </div>
    <br>
  <% end %>
<% else %>
  <p>No guesthouses found in <%= @city %></p>
<% end %>

app/views/home/index.html.erb
<nav>
  <% if @cities.present? %>
    <% @cities.each do |city| %>
      <%= link_to city, guesthouses_by_city_path(city) %>
    <% end %>
  <% else %>
    <p>No cities available</p>
  <% end %>
</nav>

<h1>Guesthouses</h1>

<div>
  <p><%= link_to 'Register Your Guesthouse', new_guesthouse_path %></p>
</div>

<p>Most Recent</p>

<% @recent_guesthouses.each do |g| %>
  <div  style='border: 1px solid'>
    <h2><%= link_to g.brand_name, g %></h2>
    <div>              
      <h3><%= g.full_address.city %> - <%= g.full_address.state %></h3>
    </div>  
  </div> 
  <br> 
<% end %>

<p>Oldest</p>

<% @other_guesthouses.each do |g| %>
  <div  style='border: 1px solid'>
    <h2><%= link_to g.brand_name, g %></h2>
    <div>              
      <h3><%= g.full_address.city %> - <%= g.full_address.state %></h3>
    </div>  
  </div> 
  <br> 
<% end %>


<% if @recent_guesthouses.empty? && @other_guesthouses.empty? %>
  <p>There is no registered guesthouse!</p>
<% end %>