config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :guesthouses, only: %i[show new create edit update] do
    get 'search', on: :collection
  end

  resources :rooms, only: %i[show new create edit update] do
    resources :custom_prices, only: %i[show new create edit update destroy]
    resources :reservations, only: %i[show new create edit update destroy show_total_price] do
      get 'show_total_price', on: :member
    end
  end

  get 'home/guesthouses_by_city/:city', to: 'home#guesthouses_by_city', as: :guesthouses_by_city

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :guesthouse

  has_many :custom_prices
  has_many :room_amenities
  has_many :amenities, through: :room_amenities
  has_many :reservations

  validates :name, :description, :maximum_guests, :dimension, :daily_price, :status, presence: true

  enum status: { disponivel: 'Disponível', indisponivel: 'Indisponível' }

  def available?(start_date, end_date, num_guests)
    reservations = Reservation.where(room: self)
                             .where.not(status: 'canceled')
                             .where('(start_date <= ? AND end_date >= ?) OR (start_date <= ? AND end_date >= ?)', start_date, start_date, end_date, end_date)

    total_guests = reservations.sum(:num_guests)

    available_capacity = maximum_guests - total_guests

    return available_capacity >= num_guests
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_guesthouse
  before_action :set_room, only: %i[show edit update]

  def new
    @room = @guesthouse.rooms.build
  end

  def create
    @room = @guesthouse.rooms.build(room_params)

    if @room.save
      redirect_to @guesthouse, notice: 'Room registered successfully!'
    else
      flash.now.alert = 'Unable to register room!'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @custom_prices = CustomPrice.all
  end

  def edit
    unless @room && current_user == @guesthouse.user
      flash.alert = "You don't have permission to edit this room!"
      redirect_to guesthouse_path
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @guesthouse, notice: 'Room updated successfully!'
    else
      flash.now.alert = 'Unable to update the room!'
      render :edit, status: :unprocessable_entity
    end
  end
end

private

def room_params
  params.require(:room).permit(
    :name,
    :description,
    :maximum_guests,
    :dimension,
    :daily_price,
    :status,
    amenity_ids: []
  )
end

def set_guesthouse
  @guesthouse = current_user.guesthouse
end

def set_room
  return if @guesthouse.nil?
  @room = @guesthouse.rooms.find_by(id: params[:id])
end

app/views/rooms/_form.html.erb
<%= form_with model: @room do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>    
  </div> 
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>    
  </div> 
  <div>
    <%= f.label :maximum_guests, 'Maximum Guests' %>
    <%= f.number_field :maximum_guests %>
  </div> 
  <div>
    <%= f.label :dimension %>
    <%= f.text_field :dimension %>    
  </div> 
  <div>
    <%= f.label :daily_price, 'Normal Price' %> $
    <%= f.text_field :daily_price %>
  </div> 
  <div>
    <%= f.label :status %>
    <%= f.select :status, ['Disponível', 'Indisponível'] %>
  </div>  

  <%= f.label :amenity_ids, 'Amenities' %>
  <%= f.collection_check_boxes :amenity_ids, Amenity.all, :id, :name %>

  <div>
    <p><%= f.submit 'Send' %></p>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<% if @room.errors.any? %>
  <p>Check the errors below:</p>
  <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<% if @room.errors.any? %>
  <p>Check the errors below:</p>
  <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>
<hr>
<%= link_to 'New Custom Price', new_room_custom_price_path(@room) %>

<h2>Custom Prices</h2>

<% if @custom_prices.any?%>
  <% @custom_prices.each do |cp| %>
    <div>
      <dl>
        <strong><dt>Daily Price:</dt></strong>
        <dd>           
          De <%= cp.start_date %> até <%= cp.end_date %>
        </dd>
        <dd>
          $<%= cp.daily_price %>
        </dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>There is no custom price</p>
<% end %>