config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :guesthouses, only: %i[show new create edit update] do
    get 'search', on: :collection
  end

  resources :rooms, only: %i[show new create edit update] do
    resources :custom_prices, only: %i[show new create edit update destroy]
    resources :reservations, only: %i[show new create edit update destroy show_total_price] do
      get 'show_total_price', on: :member
    end
  end

  get 'home/guesthouses_by_city/:city', to: 'home#guesthouses_by_city', as: :guesthouses_by_city

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/custom_price.rb
class CustomPrice < ApplicationRecord
  belongs_to :room

  validate :no_date_overlap

  private

  def no_date_overlap
    if room.custom_prices.where.not(id: id).exists?(['(start_date <= ? AND end_date >= ?)
      OR (start_date <= ? AND end_date >= ?)', start_date, start_date, end_date, end_date])
      errors.add(:base, 'There should be no overlapping dates')
    end
  end
end

app/controllers/custom_prices_controller.rb
class CustomPricesController < ApplicationController
  before_action :set_room

  def new
    @custom_price = @room.custom_prices.build
  end

  def create
    @custom_price = @room.custom_prices.new(custom_price_params)

    if @custom_price.save
      redirect_to @room, notice: 'Custom price set successfully!'
    else
      flash.now.alert = 'Unable to set custom price!'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def custom_price_params
    params.require(:custom_price).permit(:daily_price, :start_date, :end_date)
  end
end

app/views/custom_prices/new.html.erb
<h1>New Custom Price</h1>

<% if @custom_price.errors.any? %>
  <p>Check the errors below:</p>
  <ul>
    <% @custom_price.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class='custom_price-form'>
  <%= form_with model: @custom_price, url: room_custom_prices_path(@room) do |f| %>  
    <div>
      <%= f.label :daily_price, 'Daily Price $' %>
      <%= f.text_field :daily_price %>

      <%= f.label :start_date, 'Start Date' %>
      <%= f.date_field :start_date %>

      <%= f.label :end_date, 'End Date' %>
      <%= f.date_field :end_date %>
    </div>
    <div>
      <p><%= f.submit 'Send' %></p>
    </div>
  <% end %>
</div>